### PR TITLE
Introduce tox and semantic release and actually release

### PR DESCRIPTION
**Pull request by BjoernLudwig**
This is a major step in packaging and releasing the software. We test it against all current python versions and after passing the test let python-semantic-release decide if it should be released on GitHub and PyPI or not and if so, choose the correct version number.

### CODE REVIEW

**Comment by BjoernLudwigPTB** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ pyxml2pdf/PdfVisualisation/Styles.py  1
         

Complexity increasing per file
==============================
- setup.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/blus_projects/pyxml2pdf/pullRequest?prid=5140032&bid=16886182)

**Comment by BjoernLudwigPTB** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- setup.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/blus_projects/pyxml2pdf/pullRequest?prid=5140032&bid=16886182)

**Comment by BjoernLudwigPTB** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- setup.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/blus_projects/pyxml2pdf/pullRequest?prid=5140032&bid=16886182)

**Comment by BjoernLudwig** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ pyxml2pdf/PdfVisualisation/Styles.py  1
         

Complexity increasing per file
==============================
- setup.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/blus_projects/pyxml2pdf/pullRequest?prid=5140032&bid=16886182)

**Pull request merged**
